
language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - android-24
    - build-tools-23.0.3

# as per http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
sudo: false

script: "./gradlew build"

notifications:
  email: false


# deploy:
#       provider: releases
#       api_key: ""
#       file: "/app/build/outputs/app-release.apk"
#       skip_cleanup: true
#       on:
#         tags: true
  
  
