language: android
jdk:
- oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - android-24
  - build-tools-23.0.3
sudo: false
script: ./gradlew build
notifications:
  email: false
deploy:
  provider: releases
  api_key:
    secure: vYPOpHSACSFx4R9nmOiUeXMw/Glo6+XMNPUYa+9vivTuzO2u4hOusn8QRT0DL9UiQmWcAKr5w/J853b8uLo+vH7XpugDQO47aB33e2HqtfKO47Og9NLO0dpW9li9BvshdnekXoRJXQH9x2Jj9IZjphoJaFGhu3R4W0/yVj1TpEn2DiQrokr36Z2RnN39TiVLWhGJHgPdAGT99wMEJGRVO39CFlsXUj5U450BEDhJFZUHTUj3O2KF2sr6M4deE1eM/h9uovbkDl0lMqWm4EACSdpqzPjF3Z9tSadO+Grq2BKZj6LqbntstIK6R7TBmVrSCbkV7mMnNdymdnJTos1oozNAyu2TAa2v8ZSNv2b58ztsyOWcg1300tw/VIPExiuedagCnrS6e+cBqxmte4Z3B6m8uO0uMBAChv5LEPMYKrYgSfE3RQvIe3SAsW5csgZYI03sS8fT0s4qgf7kJVu95Y5WZLvTjvYPWN99J1HzztQ6L56ROwZI1Xh91Bh2Uystjj7RG2OovqyFrx3QK7bWO2IUFUKAv4fBEXY81lfmOvphE1EMHYK5vFtJbSJa0bVveYxXicAPIIOtC1HnlJCoHnhQualgAbGnEt06QeWHa5L+h1G8ZtOahBplaQUd2wR2qlGHkm47enGF+/Cj4MBHKrgjEuiWxSbJRWWFIDAPqK8=
  file: app/build/outputs/apk/app-debug.apk
  on:
    repo: Svoka/Media-provider
